CREATE TABLE users (
   id SERIAL PRIMARY KEY,
   name VARCHAR(100) NOT NULL
);

ALTER TABLE users
ADD COLUMN email VARCHAR(100) UNIQUE,
ADD COLUMN password TEXT,
ADD COLUMN role VARCHAR(20) DEFAULT 'USER',
ADD COLUMN refresh_token TEXT;

